name: deploy static website to GH pages

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # - name: Set up AWS CLI
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: $ {{ secrets.AWS_ACCESS_KEY }}
      #     aws-secret-access-key: $ {{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: us-east-1
    
      - name: Build static website
        run: |
          export REACT_APP_BACKEND_HOST=${{secrets.REACT_APP_BACKEND_HOST}} &&
          export FAST_REFRESH=$FAST_REFRESH &&
          ./render-build-cd.sh
      
      - name: Deploy to GH Pages
        run: |
          git fetch origin gh-deploy:gh-deploy
          git subtree push --prefix build origin gh-deploy

      # - name: Deploy to AWS S3
      #   run: |
      #     aws s3 sync ./build s3://customerservice-dev.soymomo.io --delete